/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ACCESS_CREDENTIALS_CHANGED_EVENT: typeof import('./utils/accessCredentials').ACCESS_CREDENTIALS_CHANGED_EVENT
  const Activity: typeof import('react').Activity
  const Fragment: typeof import('react').Fragment
  const Link: typeof import('react-router-dom').Link
  const NavLink: typeof import('react-router-dom').NavLink
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const Suspense: typeof import('react').Suspense
  const activateStoredAccessCredential: typeof import('./utils/accessCredentials').activateStoredAccessCredential
  const addDashboardPageCacheClearListener: typeof import('./utils/dashboardCache').addDashboardPageCacheClearListener
  const appConfig: typeof import('./stores/config').appConfig
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const checkAccessCredentialHealth: typeof import('./utils/accessCredentials').checkAccessCredentialHealth
  const checkStoredAccessCredentialHealth: typeof import('./utils/accessCredentials').checkStoredAccessCredentialHealth
  const clearActiveAccessCredential: typeof import('./utils/accessCredentials').clearActiveAccessCredential
  const clearDashboardPageCache: typeof import('./utils/dashboardCache').clearDashboardPageCache
  const clearDesktopApiUrl: typeof import('./utils/desktopAuthPreferences').clearDesktopApiUrl
  const clearDesktopAuthToken: typeof import('./utils/desktopAuthPreferences').clearDesktopAuthToken
  const clearDesktopStorage: typeof import('./utils/desktopStorage').clearDesktopStorage
  const create: typeof import('zustand').create
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const deleteStoredAccessCredential: typeof import('./utils/accessCredentials').deleteStoredAccessCredential
  const desktopStorageLocalStorageKeys: typeof import('./utils/desktopStorage').desktopStorageLocalStorageKeys
  const forwardRef: typeof import('react').forwardRef
  const getActiveAccessCredential: typeof import('./utils/accessCredentials').getActiveAccessCredential
  const getDesktopStorageValue: typeof import('./utils/desktopStorage').getDesktopStorageValue
  const getDocumentTitle: typeof import('./hooks/usePageTitle').getDocumentTitle
  const getStartupSettings: typeof import('./utils/startupSettings').getStartupSettings
  const hydrateDesktopAuthPreferences: typeof import('./utils/desktopAuthPreferences').hydrateDesktopAuthPreferences
  const hydrateDesktopLocalStorage: typeof import('./utils/desktopStorage').hydrateDesktopLocalStorage
  const hydrateDesktopThemePreference: typeof import('./stores/theme').hydrateDesktopThemePreference
  const isTauriRuntime: typeof import('./utils/tauri').isTauriRuntime
  const lazy: typeof import('react').lazy
  const listStoredAccessCredentials: typeof import('./utils/accessCredentials').listStoredAccessCredentials
  const memo: typeof import('react').memo
  const openExternalUrl: typeof import('./utils/openExternalUrl').openExternalUrl
  const persistDesktopApiUrl: typeof import('./utils/desktopAuthPreferences').persistDesktopApiUrl
  const persistDesktopAuthToken: typeof import('./utils/desktopAuthPreferences').persistDesktopAuthToken
  const removeDesktopLocalStorageValue: typeof import('./utils/desktopStorage').removeDesktopLocalStorageValue
  const removeDesktopStorageValue: typeof import('./utils/desktopStorage').removeDesktopStorageValue
  const saveAndActivateAccessCredential: typeof import('./utils/accessCredentials').saveAndActivateAccessCredential
  const saveStoredAccessCredential: typeof import('./utils/accessCredentials').saveStoredAccessCredential
  const setDesktopLocalStorageValue: typeof import('./utils/desktopStorage').setDesktopLocalStorageValue
  const setDesktopStorageValue: typeof import('./utils/desktopStorage').setDesktopStorageValue
  const setDesktopStorageValueAsync: typeof import('./utils/desktopStorage').setDesktopStorageValueAsync
  const setDocumentTitle: typeof import('./hooks/usePageTitle').setDocumentTitle
  const setStartupSettings: typeof import('./utils/startupSettings').setStartupSettings
  const setupExternalLinkInterceptor: typeof import('./utils/openExternalUrl').setupExternalLinkInterceptor
  const setupSiteDocument: typeof import('./utils/siteDocument').setupSiteDocument
  const setupTauriDocument: typeof import('./utils/tauri').setupTauriDocument
  const startTauriWindowDrag: typeof import('./utils/tauriWindowDrag').startTauriWindowDrag
  const startTransition: typeof import('react').startTransition
  const themeColorOptions: typeof import('./stores/theme').themeColorOptions
  const themeFontOptions: typeof import('./stores/theme').themeFontOptions
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAppUpdateStore: typeof import('./stores/update').useAppUpdateStore
  const useCCConnectEnvironmentStore: typeof import('./stores/cc-connect-environment').useCCConnectEnvironmentStore
  const useCallback: typeof import('react').useCallback
  const useClientVersion: typeof import('./hooks/useClientVersion').useClientVersion
  const useConfigStore: typeof import('./stores/config').useConfigStore
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useEnvironmentStore: typeof import('./stores/environment').useEnvironmentStore
  const useHermesAgentStore: typeof import('./stores/hermes-agent').useHermesAgentStore
  const useHermesEnvironmentStore: typeof import('./stores/hermes-environment').useHermesEnvironmentStore
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useNoticeStore: typeof import('./stores/notice').useNoticeStore
  const useOpenClawEnvironmentStore: typeof import('./stores/openclaw-environment').useOpenClawEnvironmentStore
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const usePageTitle: typeof import('./hooks/usePageTitle').usePageTitle
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useThemeStore: typeof import('./stores/theme').useThemeStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { CCConnectEnvironmentLoadState } from './stores/cc-connect-environment'
  import('./stores/cc-connect-environment')
  // @ts-ignore
  export type { EnvironmentLoadState } from './stores/environment'
  import('./stores/environment')
  // @ts-ignore
  export type { HermesEnvironmentLoadState } from './stores/hermes-environment'
  import('./stores/hermes-environment')
  // @ts-ignore
  export type { OpenClawEnvironmentLoadState } from './stores/openclaw-environment'
  import('./stores/openclaw-environment')
  // @ts-ignore
  export type { ThemeMode, ResolvedTheme, ThemeStyle, ThemeFont, ThemeColor } from './stores/theme'
  import('./stores/theme')
  // @ts-ignore
  export type { StoredAccessCredential } from './utils/accessCredentials'
  import('./utils/accessCredentials')
  // @ts-ignore
  export type { StartupPreferences, StartupSettings } from './utils/startupSettings'
  import('./utils/startupSettings')
}
